// Every source file this repository edits is text, and stays text: no file in the tree holds a literal
// C0 control character.
//
// The defect, 2026-09-16. `tools/shot.js` held a literal U+0000 and a literal U+001F — the two ends of
// the range in its `INVISIBLE` character class — and a second literal U+0000 as the string separator
// between a font key and its subject. A NUL byte makes a file read as binary, so the repository's own
// edit tool refused the whole file: `cannot edit tools/shot.js: binary file`. A worker who had found a
// real defect in that file could not fix it by editing it, and had to write a Node script to rewrite the
// file with `\u0000` and `\u001f` escapes instead. The escapes are semantically identical, so the repair
// changed no behaviour: it was proved at the time by the two regexes agreeing on all 1,112,064
// non-surrogate code points, by the separator still being exactly one U+0000, and by reversing the
// escapes reproducing the pre-repair file character for character. What it restored was the ability to
// edit the file, in a repository whose whole method is editing files. Nothing prevented the next one,
// and the failure is silent until somebody tries to edit the file. This is that check.
//
// What it reads. Every file in the tree whose name ends in one of the nine extensions below — `.js`,
// `.mjs`, `.cjs`, `.css`, `.html`, `.json`, `.md`, `.yml`, `.txt` — which is the set this repository
// authors: prose, pages, styles, data, scripts, workflows and fixtures. That was **186 file(s) when this
// gate was written on 2026-09-16, 187 an hour later as another worker's figure module landed, and 0 of them
// skipped as binary either time** — the population is the tree and the tree moves, which is why the number
// here is a snapshot and the run asserts its own denominators: files read, files skipped as binary, and two
// independent enumerations of the population agreeing, so a scan that read nothing cannot print as a pass.
//
// It walks the tree rather than asking `git ls-files`, because the files most likely to carry a stray
// byte are the ones written in the round the scan is for, and those are untracked until the commit: 15 of
// the 187 files on 2026-09-16 were new and untracked, this file and the chapter-4 pages among them.
// Ignored paths come from `.gitignore`'s own bare directory names rather than a list restated here —
// `out/` (4,800 files under it by the end of that day, every one regenerated by a gate), `node_modules/`
// (175), `progress/` — plus `.git` (602).
//
// The rule. Tab (U+0009), newline (U+000A) and carriage return (U+000D) are what a text file is made of
// and are not defects. Everything else in C0 is. An escape is not a defect: `"\u0000"` written as six
// characters in a source file is the correct form and passes, and only a literal byte fails. That
// distinction is the whole point — the repair to `tools/shot.js` was exactly that substitution — so it
// is tested in both directions on a scratch copy of a real file, in "a literal NUL in a copy" below.
// The regexes in this file are written with escapes for the same reason: a gate that had to hold literal
// control bytes to find literal control bytes could not be edited when it was wrong either.
//
// The failure is a product surface, not a bare "validation failed". Each hit is one line of
// `<file>:<line>:<column>  U+0000 NUL  — <what to write instead>`, so the message names what happened,
// which file and code point caused it, and what would satisfy it.
//
// Bound, stated because a green run here proves less than it looks:
//   - C0 only. U+007F DEL is not in C0 and is not checked, and neither are the Unicode format characters
//     a text carries invisibly (soft hyphen, zero-width space, LRM/RLM, word joiner, BOM) nor the C1
//     controls U+0080-U+009F. `tools/shot.js`'s `INVISIBLE` class still holds five of those as literals;
//     its C0 pair is written as escapes, which is what took the file out of the binary read.
//   - Encoding, not text. A file whose bytes are not valid UTF-8 — a PNG, a UTF-16 file with a BOM, whose
//     0xFF 0xFE is not UTF-8 — is skipped and counted, never failed. A BOM-less UTF-16 file of ASCII
//     text is a different case and is NOT skipped, because its bytes are valid UTF-8: NUL is a legal
//     code point, so it decodes, its NULs are reported, and the report names the file as an encoding to
//     save as UTF-8 before it tells anyone to escape a byte. Measured on 2026-09-16 by putting a UTF-16LE
//     file in the tree for one run (`out/conchar/binary-run.txt`): 52 bytes, 26 NUL bytes, read as text,
//     failed, and diagnosed as UTF-16LE rather than as 26 stray separators. Skipping it instead would
//     hide a file no tool in this repository can read.
//   - Nine extensions. A control character in `LICENSE`, `.nvmrc`, `.nojekyll` or any other name with
//     none of the nine endings is outside this scan.
//   - It reads bytes as text and judges the character, not its meaning: a NUL inside a JSON string is a
//     defect here for the same reason it was in `tools/shot.js` — the file stops being editable.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const rel = (abs) => relative(ROOT, abs).split(sep).join('/');

// ── the scope ─────────────────────────────────────────────────────────────────────────────────────
const SOURCE_EXTENSIONS = ['.js', '.mjs', '.cjs', '.css', '.html', '.json', '.md', '.yml', '.txt'];

function extensionOf(path) {
  const dot = path.lastIndexOf('.');
  return dot > path.lastIndexOf('/') + 1 ? path.slice(dot).toLowerCase() : '';
}
const inScope = (path) => SOURCE_EXTENSIONS.includes(extensionOf(path));

// The ignored paths, read from `.gitignore` rather than restated: a bare name in that file matches a
// directory at any depth, which is the rule the walks below apply. A line with a glob or a slash is
// skipped — nothing here needs the general pattern language, and guessing at it would be a second
// matcher to be wrong about. `.git` is not in `.gitignore` and is added by hand.
function ignoredDirectories() {
  const file = join(ROOT, '.gitignore');
  assert.ok(existsSync(file),
    `${rel(file)} is missing, so this scan cannot tell an ignored path from a source file. Restore it, or name the ignored directories in this test: a missing ignore list must stop the gate rather than start reading out/ (4,786 files on the tree this was written against).`);
  const names = new Set(['.git']);
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const entry = line.trim().replace(/\/+$/, '');
    if (!entry || entry.startsWith('#') || entry.startsWith('!')) continue;
    if (/[*?[\]]/.test(entry) || entry.includes('/')) continue;
    names.add(entry);
  }
  return names;
}
const IGNORED = ignoredDirectories();

// Every file on disk under a path Git tracks, by hand: a directory named in `.gitignore` is not entered.
function walkTree(dir = ROOT, found = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!IGNORED.has(entry.name)) walkTree(join(dir, entry.name), found);
    } else if (entry.isFile()) {
      found.push(rel(join(dir, entry.name)));
    }
  }
  return found;
}

// The same population a second way, because discovery that quietly stops descending leaves the first
// walk and every denominator below agreeing with each other. Node's own recursive listing, filtered by
// the same ignore names: two traversals, one ignore list.
function walkTreeWithNode() {
  const found = [];
  for (const entry of readdirSync(ROOT, { recursive: true, withFileTypes: true })) {
    const parent = entry.parentPath ?? entry.path;
    const path = rel(join(parent, entry.name));
    if (path.split('/').some((segment) => IGNORED.has(segment))) continue;
    if (entry.isFile()) found.push(path);
  }
  return found;
}

// ── the rule ──────────────────────────────────────────────────────────────────────────────────────
const ALLOWED_IN_C0 = new Set([0x09, 0x0a, 0x0d]);
// The fast path: a file with no literal C0 byte at all — most of them — never walks its characters.
const LITERAL_C0 = /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/;

const C0_NAMES = new Map(Object.entries({
  0x00: 'NUL (null)', 0x01: 'SOH', 0x02: 'STX', 0x03: 'ETX', 0x04: 'EOT', 0x05: 'ENQ', 0x06: 'ACK',
  0x07: 'BEL (bell)', 0x08: 'BS (backspace)', 0x09: 'HT (tab)', 0x0a: 'LF (newline)', 0x0b: 'VT (vertical tab)',
  0x0c: 'FF (form feed)', 0x0d: 'CR (carriage return)', 0x0e: 'SO', 0x0f: 'SI', 0x10: 'DLE', 0x11: 'DC1',
  0x12: 'DC2', 0x13: 'DC3', 0x14: 'DC4', 0x15: 'NAK', 0x16: 'SYN', 0x17: 'ETB', 0x18: 'CAN', 0x19: 'EM',
  0x1a: 'SUB (substitute)', 0x1b: 'ESC (escape)', 0x1c: 'FS', 0x1d: 'GS', 0x1e: 'RS', 0x1f: 'US (unit separator)',
  0x7f: 'DEL (delete)',
}).map(([code, name]) => [Number(code), name]));

const nameOf = (codePoint) =>
  `U+${codePoint.toString(16).toUpperCase().padStart(4, '0')}${C0_NAMES.has(codePoint) ? ` ${C0_NAMES.get(codePoint)}` : ''}`;

// Every literal C0 character in one text, with the line and column a person will open in an editor.
// The column counts characters, not UTF-16 units, so it points at the character on the screen.
function controlCharacters(text) {
  if (!LITERAL_C0.test(text)) return [];
  const found = [];
  const lines = text.split('\n');
  for (let i = 0; i < lines.length; i += 1) {
    let column = 1;
    for (const character of lines[i]) {
      const codePoint = character.codePointAt(0);
      if (codePoint < 0x20 && !ALLOWED_IN_C0.has(codePoint)) found.push({ line: i + 1, column, codePoint });
      column += 1;
    }
  }
  return found;
}

// What to write in this file's place, in the terms that file's own language reads. A control character
// is not a thing any of these formats needs; where one is genuinely meant, it is written as an escape.
function remedy(path, codePoint) {
  const hex = codePoint.toString(16).toLowerCase().padStart(4, '0');
  const extension = extensionOf(path);
  if (['.js', '.mjs', '.cjs', '.json'].includes(extension)) {
    return `${extension} reads \\u${hex} as the same character, so write that instead, or delete the character`;
  }
  if (extension === '.css') return `CSS reads \\${hex} (with a space after it) as the same character, so write that instead, or delete the character`;
  return `delete the character — ${extension} has no general escape for it — or, where the file must show one, write the text \\u${hex}`;
}

// The message. It names what happened, which file and code point caused it, what would satisfy it, and
// the denominators, because a run that compared nothing must not read like one that compared the tree.
// A file that looks like UTF-16 is named before the escapes, because for that file every escape below
// would be the wrong instruction: its bytes are an encoding, and the fix is to save it as UTF-8.
function literalReport({ hits, sources, binary }) {
  const files = [...new Set(hits.map((hit) => hit.path))];
  const encoded = files.filter((path) => hits.some((hit) => hit.path === path && hit.utf16));
  const note = encoded.length
    ? `\nBefore escaping anything, note the file(s) this is not about: ${encoded.map((path) => `${path} looks like ${hits.find((hit) => hit.path === path).utf16} — every second byte is zero`).join('; ')}. That is an encoding, not a stray byte. Save the file as UTF-8; do not write its NULs as escapes.`
    : '';
  return `${hits.length} literal C0 control character(s) in ${files.length} file(s); ${sources.length} source file(s) read, ${binary.length} skipped as binary. A literal control byte makes the file read as binary, and the repository's own edit tool then refuses the whole file: tools/shot.js held a NUL as a string separator and could not be edited at all until a script rewrote it with an escape. Every one of these characters has an escape that means the same thing, so the file's meaning does not need the byte — staying editable is the point.\n  ${hits.map((hit) => `${hit.path}:${hit.line}:${hit.column}  ${nameOf(hit.codePoint)} — ${remedy(hit.path, hit.codePoint)}`).join('\n  ')}${note}`;
}

// A UTF-16 file that carries only ASCII is valid UTF-8, so the decoder above cannot tell it from a text
// file with a stray NUL, and would report every second byte as a defect to escape. The byte pattern is
// what gives it away: in UTF-16LE every second byte is zero, in UTF-16BE every first one is. Nothing else
// matches — a file of nothing but zero bytes has no characters at all and stays a defect, and the isolated
// NULs of the pre-repair `tools/shot.js` (the red proof below) do not alternate — so a real stray byte is
// never excused as an encoding. A UTF-16 file with a BOM never reaches this test: 0xFF is not valid UTF-8
// and the decode has already rejected it.
function looksLikeUtf16(bytes) {
  if (bytes.length < 4) return null;
  const sample = bytes.subarray(0, Math.min(bytes.length, 64));
  const pairs = Math.floor(sample.length / 2);
  let oddZero = 0;
  let evenZero = 0;
  for (let i = 0; i + 1 < sample.length; i += 2) {
    if (sample[i + 1] === 0) oddZero += 1;
    if (sample[i] === 0) evenZero += 1;
  }
  // Little-endian is every odd byte zero with the even half carrying the text; big-endian is the other
  // way round. `pairs - otherZero > 0` is what excludes a file of nothing but zero bytes, which fills
  // both halves with zeros and has no text in either.
  if (oddZero === pairs && pairs - evenZero > 0) return 'UTF-16LE';
  if (evenZero === pairs && pairs - oddZero > 0) return 'UTF-16BE';
  return null;
}

// The text of one source file, or null when its bytes are not UTF-8. A binary file wearing a source
// file's name is skipped and counted: a UTF-16 file with a BOM is one, and so is a PNG someone renamed.
const DECODER = new TextDecoder('utf-8', { fatal: true });
function scanFile(path) {
  const bytes = readFileSync(join(ROOT, path)); // a file the walk listed and cannot read is a real failure
  let text;
  try {
    text = DECODER.decode(bytes);
  } catch {
    return null;
  }
  return { hits: controlCharacters(text), utf16: looksLikeUtf16(bytes) };
}

function census() {
  const population = walkTree().filter(inScope).sort();
  const sources = [];
  const binary = [];
  const hits = [];
  for (const path of population) {
    const scanned = scanFile(path);
    if (scanned === null) {
      binary.push(path);
      continue;
    }
    sources.push(path);
    for (const hit of scanned.hits) hits.push({ ...hit, path, utf16: scanned.utf16 });
  }
  return { population, sources, binary, hits };
}

// ── the gate ──────────────────────────────────────────────────────────────────────────────────────

test('no source file in the tree holds a literal C0 control character', (t) => {
  const { population, sources, binary, hits } = census();
  t.diagnostic(`control-chars: ${sources.length} source file(s) read, ${binary.length} skipped as binary, ${population.length} in scope, ${hits.length} literal C0 character(s)`);
  assert.ok(sources.length > 0,
    `${population.length} file(s) were in scope and not one could be read as text, so this scan compared nothing and must not pass. Either the tree is missing, or the walk is, or every file it found is binary.`);
  assert.equal(sources.length + binary.length, population.length,
    `${population.length} file(s) in scope, ${sources.length} read and ${binary.length} skipped as binary — the two do not add up, so a file was dropped without being counted`);
  assert.equal(hits.length, 0, literalReport({ hits, sources, binary }));
});

test('the rule is the whole of C0 except tab, newline and carriage return', () => {
  const everyC0 = [...Array(0x20).keys()];
  const flagged = controlCharacters(String.fromCodePoint(...everyC0)).map((hit) => hit.codePoint);
  assert.deepEqual(flagged, everyC0.filter((codePoint) => !ALLOWED_IN_C0.has(codePoint)),
    `every C0 character except tab, newline and carriage return must be reported. Reported: ${flagged.map(nameOf).join(', ')}`);

  // Named, because "not reported" and "not looked at" produce the same output, and these three are the
  // reason the rule has an exception at all.
  for (const codePoint of ALLOWED_IN_C0) {
    assert.ok(!flagged.includes(codePoint), `${nameOf(codePoint)} is not a defect: every text file in the tree needs it`);
  }

  // And the bound this gate does not cross, asserted so a later reader does not take it for coverage:
  assert.deepEqual(controlCharacters('a\u007fb').map((hit) => hit.codePoint), [],
    'U+007F DEL is outside C0 and this gate does not check it; neither are the C1 controls U+0080-U+009F nor the invisible format characters, as the header says');
  assert.deepEqual(controlCharacters('a\u00adb\u200bc\ufeffd').map((hit) => hit.codePoint), [],
    'a soft hyphen, a zero-width space and a BOM are not C0 and are not this gate\'s subject, whatever a file does with them');

  // The line and column, on the shape the defect actually had: a NUL used as a separator inside a string.
  const text = 'const first = "a";\nconst key = `a\u0000b`;\nconst last = "c";\n';
  const hits = controlCharacters(text);
  assert.equal(hits.length, 1, `one literal NUL in a three-line string gave ${hits.length} hit(s)`);
  assert.deepEqual({ line: hits[0].line, column: hits[0].column, codePoint: hits[0].codePoint },
    { line: 2, column: text.split('\n')[1].indexOf('\u0000') + 1, codePoint: 0 },
    'the hit must name the line and the column a person opening the file will see');

  // A column counts characters, not UTF-16 units: one astral character before the NUL is one column.
  assert.deepEqual(controlCharacters('\u{1D11E}\u0000').map((hit) => hit.column), [2],
    'a column that counted UTF-16 units would point one place to the right of the character after any astral character');
});

test('a literal NUL in a copy of a real file fails, and the same code point written as an escape passes', (t) => {
  // The defect's own shape, in scratch: a NUL byte in a file that is otherwise ordinary source. The two
  // arms are a copy of a real tracked file with the one character under test added, so they differ by
  // that character and nothing else. No real file is modified to prove this.
  const donor = 'tools/lib/trim.js';
  const donorBytes = readFileSync(join(ROOT, donor));
  const text = donorBytes.toString('utf8');
  const lines = text.split('\n');
  const column = 20;
  assert.ok(lines[0].length > column,
    `the first line of ${donor} is ${lines[0].length} character(s) long, so the injection point this proof uses (column ${column + 1}) is past its end. Point the proof at another line rather than deleting it: what it proves is that a literal byte is found wherever it sits in a file.`);
  const withMarker = (marker) => [lines[0].slice(0, column) + marker + lines[0].slice(column), ...lines.slice(1)].join('\n');

  const scratch = join(ROOT, 'out', 'conchar');
  mkdirSync(scratch, { recursive: true });
  const redPath = join(scratch, 'literal-nul.js');
  const greenPath = join(scratch, 'escaped-nul.js');
  writeFileSync(redPath, withMarker('\u0000'), 'utf8');   // one NUL byte
  writeFileSync(greenPath, withMarker('\\u0000'), 'utf8'); // the six characters an escape is written with

  // Red. The byte is on disk, the scan finds it, and the message names it. The two arms are compared in
  // BYTES, not characters: the donor holds em dashes and ellipses, which are three bytes and one
  // character each, so a character count would not say what was added.
  assert.equal([...readFileSync(redPath)].filter((byte) => byte === 0).length, 1,
    'the red arm of this proof has no NUL byte in it, so it proves nothing about a NUL byte');
  assert.equal(readFileSync(redPath).length, donorBytes.length + 1,
    `the red arm must be the donor plus exactly one byte — ${readFileSync(redPath).length} bytes against the donor's ${donorBytes.length} — or it is not a proof about one byte`);
  const redHits = scanFile(rel(redPath)).hits;
  assert.equal(redHits.length, 1, `the red arm gave ${redHits.length} hit(s) for one literal NUL`);
  assert.deepEqual({ line: redHits[0].line, column: redHits[0].column, codePoint: redHits[0].codePoint },
    { line: 1, column: column + 1, codePoint: 0 }, 'the hit must point at the byte that was put there');
  assert.equal(scanFile(rel(redPath)).utf16, null,
    'one isolated NUL is not an encoding: a file that alternates zero bytes is the UTF-16 case below, and this one must not be excused as it');

  const message = literalReport({ hits: redHits.map((hit) => ({ ...hit, path: rel(redPath), utf16: null })), sources: [rel(redPath)], binary: [] });
  for (const expected of [`${rel(redPath)}:1:${column + 1}`, 'U+0000 NUL (null)', '\\u0000', '1 source file(s) read', '0 skipped as binary']) {
    assert.ok(message.includes(expected),
      `the failure message does not say ${JSON.stringify(expected)}, so a reader cannot tell which file, which code point, or what to write instead:\n${message}`);
  }
  t.diagnostic(`red arm, one literal NUL in a copy of ${donor} — the failure this gate prints:\n${message}`);

  // Green. The same code point, written as the six characters every one of these languages reads as it:
  // no literal byte, and the scan that failed the red arm passes this one.
  const greenBytes = readFileSync(greenPath);
  assert.equal([...greenBytes].filter((byte) => byte === 0).length, 0,
    'the green arm is supposed to hold no literal NUL byte; without that it is not the other direction');
  assert.ok(greenBytes.toString('utf8').includes('\\u0000'),
    'the green arm does not contain the six characters \\u0000, so it passes the scan by saying nothing about the escape rather than by holding it');
  assert.equal(greenBytes.length, donorBytes.length + 6,
    `the green arm must be the donor plus exactly the six bytes of the escape — ${greenBytes.length} bytes against the donor's ${donorBytes.length} — so the two arms differ by the byte under test and nothing else`);
  assert.deepEqual(scanFile(rel(greenPath)).hits, [],
    'the escape form is the correct form and must pass: only a literal byte is a defect');
  t.diagnostic(`green arm, the same character as ${'\\u0000'} in a copy of ${donor}: 0 hit(s), 0 literal NUL bytes in ${greenBytes.length} bytes`);
});

test('a BOM-less UTF-16 file is read, failed, and named an encoding rather than escaped', () => {
  // The one case where the remedy in the message would be the wrong instruction, and the reason it is
  // detected rather than skipped: this file's bytes ARE valid UTF-8 (NUL is a legal code point), so
  // skipping it would hide a file no tool here can read, and failing it without the note would tell a
  // person to escape 26 bytes that are one file's encoding.
  const le = Buffer.from('const a = 1;\n', 'utf16le');
  assert.equal(le.toString('utf8').length > 0, true, 'the UTF-16 bytes must decode, or this is the skip path and not this one');
  assert.equal(looksLikeUtf16(le), 'UTF-16LE', 'a UTF-16LE file is every second byte zero, and must be recognised');
  const be = Buffer.from(le).swap16();
  assert.equal(looksLikeUtf16(be), 'UTF-16BE', 'the same file big-endian is every first byte zero');

  // The pattern is strict, so a real stray byte is never excused as an encoding:
  assert.equal(looksLikeUtf16(Buffer.from('const key = `${a}\u0000${b}`;\n', 'utf8')), null,
    'an isolated NUL in ordinary source is the defect this gate exists for, not an encoding');
  assert.equal(looksLikeUtf16(Buffer.alloc(64)), null,
    'a file of nothing but zero bytes has no characters at all, so it is not UTF-16 text: it stays a defect rather than being skipped');
  assert.equal(looksLikeUtf16(Buffer.from('ab', 'utf8')), null, 'a file too short to have a pattern is read as text');

  // And the report says which file it is about, before the escapes it is not about:
  const hits = controlCharacters(le.toString('utf8')).map((hit) => ({ ...hit, path: 'saved-as-utf16.js', utf16: 'UTF-16LE' }));
  const message = literalReport({ hits, sources: ['saved-as-utf16.js'], binary: [] });
  assert.ok(hits.length >= 10, `a UTF-16LE ASCII file holds one NUL per character and gave ${hits.length} hit(s)`);
  assert.ok(message.includes('saved-as-utf16.js looks like UTF-16LE'),
    `the report must name the file as an encoding rather than leaving it to the escape lines:\n${message}`);
  assert.ok(message.includes('Save the file as UTF-8'),
    `the report must say what would satisfy it, and for this file that is a re-encoding, not an escape:\n${message}`);
});

test('the population is the tree, enumerated twice, and the ignored paths really hold files', (t) => {
  const mine = walkTree().filter(inScope).sort();
  const theirs = walkTreeWithNode().filter(inScope).sort();
  const only = (a, b) => a.filter((path) => !b.includes(path));
  assert.ok(mine.length > 0, 'this walk found no source file at all, so the census above compared nothing');
  assert.deepEqual(mine, theirs,
    `two enumerations of the tree disagree about which source files exist, so one of them is not reading the tree: only in the hand walk — ${only(mine, theirs).join(', ') || '(none)'}; only in Node's recursive walk — ${only(theirs, mine).join(', ') || '(none)'}`);

  // The files this gate must read, one per directory and extension family. If the walk stops descending
  // anywhere, or the ignore list grows over a source directory, one of these goes missing and says so:
  // a census over a shrinking population is how a gate goes green over a tree it stopped reading.
  const MUST_READ = [
    'README.md', '.github/workflows/pages.yml', 'package.json',
    'src/palette.js', 'src/styles/tokens.css', 'src/figures/registry.js',
    'tools/shot.js', 'tools/lib/trim.js', 'test/control-chars.test.js', 'test/fixtures/traditional-only.txt',
    'biology/ch01-what-is-life/index.html', 'biology/ch01-what-is-life/glossary.js',
    'tongjian/zj.css', 'today/index.html', 'docs/policies/local-rules.md',
  ];
  const population = new Set(mine);
  const missing = MUST_READ.filter((path) => !population.has(path));
  assert.deepEqual(missing, [],
    `these source file(s) are on disk and are not in the population: ${missing.join(', ')}. If one was renamed, point this list at where it went; do not delete the row — a file that leaves the population leaves the gate silently. tools/shot.js is the file this gate exists for: it held a literal NUL as a string separator and could not be edited until the byte became an escape.`);

  // The ignored paths, checked because an exclusion that excludes nothing is not an exclusion: where one
  // of these directories exists it holds files, and no file under it is in the population. A directory
  // that is not on the tree at all — `out/` on a fresh clone, before any gate has written there — is
  // named as absent rather than silently passed over, so a run cannot read as proving an exclusion it
  // never made.
  const everyEntry = readdirSync(ROOT, { recursive: true, withFileTypes: true });
  const absent = [];
  const held = [];
  for (const name of ['.git', 'node_modules', 'out']) {
    assert.ok(IGNORED.has(name),
      `.gitignore no longer names ${name}/, so this walk derives an ignore list without it and would read whatever is in there. If ${name}/ is no longer ignored, say here what should be read instead.`);
    if (!existsSync(join(ROOT, name))) {
      absent.push(name);
      continue;
    }
    const inside = everyEntry.filter((entry) => {
      const path = rel(join(entry.parentPath ?? entry.path, entry.name));
      return entry.isFile() && path.startsWith(`${name}/`);
    }).length;
    assert.ok(inside > 0, `${name}/ is on disk and holds no file, so excluding it proves nothing about this walk`);
    assert.deepEqual(mine.filter((path) => path.startsWith(`${name}/`)), [],
      `the walk read file(s) under ${name}/, which is ignored: ${mine.filter((path) => path.startsWith(`${name}/`)).join(', ')}`);
    held.push(`${name}/ ${inside}`);
  }
  t.diagnostic(`control-chars population: ${mine.length} source file(s) by hand and by Node's recursive walk; ignored directories checked and holding files — ${held.join(', ') || '(none on this tree)'}; not on this tree — ${absent.join(', ') || '(none)'}`);
});
