// Chapter 1 glossary. Every <tb-term ref="..."> in index.html names a key here, and every key here is
// used in the chapter at least once (npm run check enforces both). `def` may hold inline HTML.
export const GLOSSARY = {
  biology: { term: 'Biology', def: 'The scientific study of living things and of life itself: how organisms are built, how they work, how they came to be, and how they interact.' },
  organism: { term: 'Organism', def: 'An individual living thing, whether one cell or trillions, that carries out the properties of life on its own.' },
  cell: { term: 'Cell', def: 'The smallest unit that is alive on its own: a membrane-bound volume of ordered chemistry that grows, uses energy and, in most cases, divides.' },
  metabolism: { term: 'Metabolism', def: 'The sum of the chemical reactions by which an organism takes in matter and energy and transforms them, building up what it needs and breaking down what it does not.' },
  homeostasis: { term: 'Homeostasis', def: 'The maintenance of a steady internal state, such as temperature, water content or acidity, in the face of a changing environment.' },
  'negative-feedback': { term: 'Negative feedback', def: 'A control loop in which the response to a change opposes that change, pushing a quantity back towards its set point. Most homeostatic loops are of this kind.' },
  'set-point': { term: 'Set point', def: 'The value a control loop defends, such as a core temperature of about 37\u00A0°C. A fever is a set point moved up on purpose.' },
  hypothalamus: { term: 'Hypothalamus', def: 'A small region at the base of the brain that compares sensed values with their set points and commands the body\'s responses, including those that hold temperature.' },
  emergence: { term: 'Emergent property', def: 'A property of a whole that none of its parts has alone, arising from how the parts are arranged and interact: a heart pumps, a heart cell does not.' },
  organelle: { term: 'Organelle', def: 'A structure inside a cell with a particular job, such as the nucleus, a mitochondrion or the Golgi apparatus. In eukaryotic cells most organelles are wrapped in their own membranes.' },
  prokaryote: { term: 'Prokaryote', def: 'A cell with no nucleus: its DNA lies in the cytoplasm. Bacteria and archaea are prokaryotes, typically 1–\u20605\u00A0µm across.' },
  eukaryote: { term: 'Eukaryote', def: 'A cell whose DNA is held inside a nucleus, with other membrane-bound organelles around it. Animals, plants, fungi and many single-celled organisms are eukaryotes.' },
  nucleus: { term: 'Nucleus', def: 'The membrane-bound compartment of a eukaryotic cell that holds its chromosomes.' },
  'cell-theory': { term: 'Cell theory', def: 'Three claims: all living things are made of cells, the cell is the smallest unit of life, and every cell comes from a pre-existing cell.' },
  dna: { term: 'DNA', def: 'Deoxyribonucleic acid: the double-stranded molecule in which every known organism stores its genetic information, written as the order of four bases.' },
  'base-pair': { term: 'Base pair', def: 'One rung of the DNA ladder: adenine paired with thymine, or guanine paired with cytosine, held together by hydrogen bonds.' },
  gene: { term: 'Gene', def: 'A stretch of DNA that specifies a product, usually a protein and sometimes an RNA, and is passed from parent to offspring.' },
  genome: { term: 'Genome', def: 'The complete set of an organism\'s DNA. The human genome is about 3.1\u00A0billion base pairs.' },
  producer: { term: 'Producer', def: 'An organism that makes its own food from sunlight (or, more rarely, from chemical energy), such as a plant, an alga or a photosynthetic bacterium.' },
  consumer: { term: 'Consumer', def: 'An organism that gets its energy by eating other organisms.' },
  decomposer: { term: 'Decomposer', def: 'An organism, usually a fungus or a bacterium, that breaks down dead matter and waste, returning its atoms to the soil, water and air.' },
  evolution: { term: 'Evolution', def: 'Change in the inherited characteristics of a population across generations. It is the process that made living things related to one another and fitted to their ways of life.' },
  'natural-selection': { term: 'Natural selection', def: 'The mechanism Darwin and Wallace described: inherited variation, more offspring than can survive, and greater reproductive success for the variants that suit the environment.' },
  adaptation: { term: 'Adaptation', def: 'An inherited feature that fits an organism to its environment and was shaped by natural selection; also the process that produces such features.' },
  domain: { term: 'Domain', def: 'The broadest grouping of life. There are three: Bacteria, Archaea and Eukarya.' },
  endosymbiosis: { term: 'Endosymbiosis', def: 'One cell living inside another. Mitochondria and chloroplasts descend from bacteria that were taken into ancestral cells and stayed.' },
  hypothesis: { term: 'Hypothesis', def: 'A proposed explanation that makes testable predictions. It earns trust by surviving attempts to prove it wrong, and is discarded when it fails them.' },
  theory: { term: 'Theory', def: 'In science, a broad explanation supported by a large body of evidence that has survived every careful test so far, such as cell theory or the theory of evolution. Not a guess.' },
  control: { term: 'Controlled experiment', def: 'A test in which one condition is changed while every other condition is held the same, so any difference in outcome can be traced to that one change.' },
  'spontaneous-generation': { term: 'Spontaneous generation', def: 'The old belief that living things arise directly from non-living matter, such as maggots from meat. Redi and Pasteur showed that they do not.' },
  micrometre: { term: 'Micrometre (µm)', def: 'One millionth of a metre, the unit cells are measured in. A nanometre (nm) is a thousand times smaller and is the unit for molecules.' },
};
